unique_ids:
  assets:
    standard-page.html: SERFB64JTU7KQI46ZZT3TOCSAHM232LX
    theme.css: 2R7GM7J3WTV3GDPPV376AGVHWOK5E5SO
  forms:
    Form1: H4JBZWZR3BK5CAIHHS3O6H4PJ3FF4UUS
  modules: {}
  scripts: {}
  server_modules: {}
